### ISSUE TITLE
CUDA build dependency is unacceptable

### ISSUE THREAD

**Issue by drws** [Lurkki14/tuxclocker#57]
CUDA seems to be a new build dependency in TuxClocker v1.0. CUDA It is a 5GB-sized framework for additional computation capabilities and at first glance it seems like something that _a hardware controlling and monitoring program_ wouldn't even need. Even if it's needed due to some NVIDIA incompetency, that's business as usual, but TuxClocker should still work around it or simply drop the functionality that needs a 5GB GPGPU framework.

**Comment by Lurkki14** [comment]
Indeed TuxClocker doesn't make use of that whole 5GB, but only `libnvml.so` is used as you can see here https://github.com/Lurkki14/tuxclocker/blob/master/src/plugins/meson.build#L21. Cuda is just mentioned since some distros (like NixOS) only ship `libnvml.so` in a huge blob called `cudatoolkit` or the like. I'll update the readme in a bit to clarify this.

**Comment by Lurkki14** [comment]
https://github.com/Lurkki14/tuxclocker/commit/4777de438e40dbccf00526814d45b8daf7f581bc

**Comment by drws** [comment]
Thank you for clarifying the situation and sorry for a bit strongly-worded title which possibly changed the tone of the whole text. I skipped the title box in my final overlook while in a hurry. And also shouldv'e thought of the other upstream possibility :)
